spring:
  profiles:
    default: prod

  datasource:
    url: jdbc:mysql://localhost:3306/practice?characterEncoding=utf8
    username: root
    password: 'youprodb'
    driver-class-name: com.mysql.cj.jdbc.Driver
  server:
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 100MB  

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        
server:
  error:
    include-stacktrace: never